# Generated by Django 5.0.6 on 2024-06-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_heartvital_prediction_probability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartvital',
            name='FastingBS',
            field=models.CharField(choices=[('0', 'less than or equal to 120'), ('1', 'More than to 120')], max_length=20, verbose_name='Fasting Blood Pressure'),
        ),
        migrations.AlterField(
            model_name='heartvital',
            name='MaxHR',
            field=models.IntegerField(verbose_name='Max Heart Rate'),
        ),
        migrations.AlterField(
            model_name='heartvital',
            name='RestingBP',
            field=models.IntegerField(verbose_name='Resting Blood Pressure'),
        ),
        migrations.AlterField(
            model_name='heartvital',
            name='RestingECG',
            field=models.CharField(choices=[('Normal', 'Normal'), ('ST', 'having ST-T wave abnormality'), ('LVH', "showing probable or definite left ventricular hypertrophy by Estes' criteria")], max_length=20, verbose_name='Resting ECG Condition'),
        ),
    ]
